- name: ADA
  class: ADATrainer
  params:
    # size of the training batch
    batch_size: 256

    # Number of latent dimensions
    z_dim: 64
    x_dim: 392
    # load_encoder: 'experiments/VAE_short_train_beta05_0/wandb/run-20200605_120530-VAE_short_train_beta05_0/model.pt'

    # Optimization parameters
    optimizer_name: 'RMSprop'
    encoder_lr: 0.0001
    ce_lr: 0.00005
    n_ce_steps: 50
    dist: Delta

    # Parameters for the beta-scheduler
    beta_start_value: 0.00001
    beta_end_value: 0.99999
    beta_n_iterations: 20000
    beta_start_iteration: 20000

