class: CICMITrainer
params:
  # Number of latent dimensions
  z_dim: 2

  #################
  # Architectures #
  #################

  # Encoder
  encoder:
    class: 'SimpleEncoder'
    params:
      dist: 'Delta'
      dropout: 0

  # Label classifier
  joint_classifier:
    class: 'SimpleJointClassifier'

  mi_estimator:
    class: 'SimpleMIEstimator'

  ###########################
  # Optimization parameters #
  ###########################

  # Optimizer used for the encoder and the label classifier
  optim:
    class: 'Adam'
    params:
      lr: 0.0001

  # Size of the training batch
  batch_size: 256

  n_adv_steps: 5

  # Parameters for the beta-scheduler
  beta_scheduler:
    class: LinearScheduler
    params:
      start_value: 0.99
      end_value: 0.99
      n_iterations: 10000
      start_iteration: 5000
