class: ECITrainer
params:
  # Number of latent dimensions
  z_dim: 64

  #################
  # Architectures #
  #################

  # Encoder
  encoder:
    class: 'SimpleEncoder'
    params:
      dist: 'Delta'

  # Label classifier
  classifier:
    class: 'SimpleClassifier'

  # Environment Classifier
  env_classifier:
    class: 'SimpleConditionalEnvClassifier'

  ###########################
  # Optimization parameters #
  ###########################

  # Optimizer used for the encoder and the label classifier
  optim:
    class: 'Adam'
    params:
      lr: 0.0001

  # Adversarial optimizer used for training the environment classifier
  adv_optim:
    class: 'Adam'
    params:
      lr: 0.0001

  # Size of the training batch
  batch_size: 256

  # Adversarial objective
  adv_objective: CE

  # Adversarial optimization strategy (simultaneous/alternating)
  adv_train_type: alternating

  # Number of adversarial steps for each optimizer step (only for alternating training)
  n_adv_steps: 5

  # Parameters for the beta-scheduler
  beta_scheduler:
    class: SigmoidScheduler
    params:
      start_value: 0.00001
      end_value: 0.9999999
      n_iterations: 50000
      start_iteration: 10000
