class: ERMTrainer
params:
  # Number of latent dimensions
  z_dim: 64

  #################
  # Architectures #
  #################

  # Encoder
  encoder:
    dropout: 0.25
    n_hidden: 128
    dist: Delta

  # Label classifier
  label_classifier:
    dropout: 0.0
    n_hidden: 128

  ###########################
  # Optimization parameters #
  ###########################

  # Optimizer used for the encoder and the label classifier
  optim:
    class: Adam
    params:
      lr: 0.0001

  # Size of the training batch
  batch_size: 256
