- name: IDA_v2
  class: IDAV2Trainer
  params:
    # size of the training batch
    batch_size: 64

    # Number of latent dimensions
    z_dim: 64
    n_classes: 2
    n_env: 2

    # Optimization parameters
    optimizer_name: 'Adam'
    encoder_lr: 0.001

