class: IDAACETrainer
params:
  # Number of latent dimensions
  z_dim: 2

  #################
  # Architectures #
  #################

  # Encoder
  encoder:
    class: 'SimpleEncoder'
    params:
      dist: 'Delta'

  # Label classifier
  classifier:
    class: 'ConstantClassifier'

  # Environment Classifier
  env_classifier:
    class: 'SimpleConditionalEnvClassifier'

  ###########################
  # Optimization parameters #
  ###########################

  # Optimizer used for the encoder and the label classifier
  optim:
    class: 'RMSprop'
    params:
      lr: 0.0005

  # Adversarial optimizer used for training the environment classifier
  adv_optim:
    class: 'RMSprop'
    params:
      lr: 0.0005

  # Number of adversarial steps for each optimizer step
  n_adv_steps: 20

  # Size of the training batch
  batch_size: 64

  # Parameters for the beta-scheduler
  beta_scheduler:
    class: ExponentialScheduler
    params:
      start_value: 0.00001
      end_value: 0.9999999
      n_iterations: 20000
      start_iteration: 10000
