class: IDAACETrainer
params:
  # Number of latent dimensions
  z_dim: 2

  #################
  # Architectures #
  #################

  # Encoder
  encoder:
    class: 'SimpleEncoder'
    params:
      dist: 'Delta'
      dropout: 0.5

  # Label classifier
  classifier:
    class: 'SimpleClassifier'

  # Environment Classifier
  env_classifier:
    class: 'SimpleConditionalEnvClassifier'

  ###########################
  # Optimization parameters #
  ###########################

  # Optimizer used for the encoder and the label classifier
  optim:
    class: 'RMSprop'
    params:
      lr: 0.0001

  # Non alternating procedure, both encoder and discriminator are trained at the same time using a
  # gradient reversal layer
  adv_train_type: simultaneous

  # Size of the training batch
  batch_size: 256

  # Parameters for the beta-scheduler
  beta_scheduler:
    class: LinearScheduler
    params:
      start_value: 0.5
      end_value: 0.9999
      n_iterations: 20000
      start_iteration: 10000
