class: JICMITrainer
params:
  # Number of latent dimensions
  z_dim: 64

  #################
  # Architectures #
  #################

  method: 'jsd'

  # Encoder
  encoder:
    class: 'SimpleEncoder'
    params:
      dist: 'Normal'
      dropout: 0

  # Label classifier
  env_classifier:
    class: 'SimpleConditionalEnvClassifier'

  env_mi_estimator:
    class: 'SimpleMIEstimator'

  classifier:
    class: 'SimpleClassifier'

  mi_estimator:
    class: 'SimpleMIEstimator'

  ###########################
  # Optimization parameters #
  ###########################

  # Optimizer used for the encoder and the label classifier
  optim:
    class: 'RMSprop'
    params:
      lr: 0.0001

  adv_optim:
    class: 'RMSprop'
    params:
      lr: 0.0001


  # Size of the training batch
  batch_size: 512

  n_adv_steps: 50

  # Parameters for the beta-scheduler
  beta_scheduler:
    class: LinearScheduler
    params:
      start_value: 0.99999
      end_value: 0.99999
      n_iterations: 10000
      start_iteration: 5000
