- name: VAE
  class: VAETrainer
  params:
    # Number of latent dimensions
    z_dim: 64
    x_dim: 392

    batch_size: 64

    # Optimization parameters
    optimizer_name: 'Adam'
    encoder_lr: 0.0001
    decoder_lr: 0.0001

    # Parameters for the beta-scheduler
    beta_start_value: 0.001
    beta_end_value: 0.5
    beta_n_iterations: 5000
    beta_start_iteration: 5000

