- name: test_accuracy_0.1
  class: LinearAccuracyEvaluation
  params:
    train_on: train_set
    test_on: test_set_0.1
- name: test_accuracy_0.2
  class: LinearAccuracyEvaluation
  params:
    train_on: train_set
    test_on: test_set_0.2
- name: test_accuracy_0.9
  class: LinearAccuracyEvaluation
  params:
    train_on: train_set
    test_on: test_set_0.9
