- name: IDA_v3
  class: IDAV3Trainer
  params:
    # size of the training batch
    batch_size: 64

    # Number of latent dimensions
    z_dim: 2
    n_classes: 2
    n_env: 2
    f_dim: 64
    k: 10

    # Optimization parameters
    optimizer_name: 'Adam'
    encoder_lr: 0.001

    # Parameters for the beta-scheduler
    beta_start_value: 0.5
    beta_end_value: 1
    beta_n_iterations: 100000
    beta_start_iteration: 10000

