- name: test_accuracy/0.1
  class: LinearAccuracyEvaluation
  model: encoder
  params:
    train_on: representation_train_set
    test_on: test_set_0.1

- name: test_accuracy/0.2
  class: LinearAccuracyEvaluation
  model: encoder
  params:
    train_on: representation_train_set
    test_on: test_set_0.2

- name: test_accuracy/0.9
  class: LinearAccuracyEvaluation
  model: encoder
  params:
    train_on: representation_train_set
    test_on: test_set_0.9
