class: VIBTrainer
params:
  # Number of latent dimensions
  z_dim: 64

  #################
  # Architectures #
  #################

  # Encoder
  encoder_layers: [1024, 256]

  # Label classifier
  classifier_layers: [256, 128]

  ###########################
  # Optimization parameters #
  ###########################

  # Learning Rate
  lr: 0.0001

  # Size of the training batch
  batch_size: 256

  # Read the number of workers from the environment variable
  num_workers: ${NUM_WORKERS}

  ##########################
  # Other model parameters #
  ##########################
  beta: 0.5
